:icons: font
:ci: https://github.com/devtty/webcastellum/actions?query=workflow%3A%22Java+CI%22
:sonar: https://sonarcloud.io/dashboard?id=devtty_webcastellum

image:https://github.com/devtty/webcastellum/workflows/Java%20CI/badge.svg?branch=main[link={ci}]
image:https://sonarcloud.io/api/project_badges/measure?project=devtty_webcastellum&metric=alert_status["Quality Gate Status", link={sonar}]
image:https://img.shields.io/ossf-scorecard/github.com/devtty/webcastellum?label=openssf%20scorecard&style=flat[]

== WebCastellum

Java-based Open Source WAF (Web Application Firewall) to include inside a web application in order to protect it against attacks like SQL Injection, Cross-Site Scripting (XSS), Cross-Site Request Forgery (CSRF), Parameter Manipulation and many more.

This quickstart readme contains the minimum steps required to integrate the WebCastellum Web Application Firewall 
into the WAR archive of a web application. Further information on the installation as well as detailed instructions 
for activating and customizing the numerous protection functions offered can be found in the https://github.com/devtty/webcastellum/wiki/files/WebCastellumGuideEnglish.pdf[WebCastellum 
Reference Guide] .
// Further information can be found at http://www.WebCastellum.org and in the WebCastellum Forum at http://forum.WebCastellum.org

=== Basic installation and configuration of WebCastellum

. unpack the WAR archive of the web application

. copy the webcastellum.jar into the WEB-INF/lib directory

. adaptation of the web.xml:

.. Definition of a new servlet filter

IMPORTANT: Filter must be defined before any other filters

[source,xml]
----
  <filter>
    <filter-name>WebCastellum</filter-name>
    <filter-class>org.webcastellum.WebCastellumFilter</filter-class>
    <init-param>
      <param-name>ApplicationName</param-name>
      <!-- Name of the application (relevant for logging) -->
      <param-value>MyApplication</param-value>
    </init-param>
      <init-param>
        <param-name>RedirectWelcomePage</param-name>
        <!-- Redirect target (absolutely defined) to the login screen of the application to be protected -->
        <param-value>/MyApplication/</param-value>
      </init-param>
      <init-param>
         <param-name>CharacterEncoding</param-name>
         <!-- The most common encodings are ISO-8859-1 or UTF-8 depending on the web application to be protected -->
         <param-value>ISO-8859-1</param-value>
      </init-param>
      <init-param>
          <param-name>AttackLogDirectory</param-name>
          <!-- Logging folder (either relative to the JVM root or absolutely definable) -->
          <param-value>logs</param-value>
      </init-param>
      <init-param>
          <param-name>DefaultProductionModeCheckerValue</param-name>
          <!-- Please set to “true” if productive use is to take place, so that no detailed information texts are displayed in the event of attacks are displayed, as is the case in development mode. -->
          <param-value>false</param-value>
      </init-param>
      <init-param>
          <param-name>TransparentForwarding</param-name>
          <!-- Depending on the web framework used, set to “true” or “false” (see below). -->
          <param-value>false</param-value>
      </init-param>
      <init-param>
           <param-name>TransparentQueryString</param-name>
           <param-value>false</param-value>
      </init-param>
      <!-- 
                    ...
                    ...
                    ...
                    The other numerous protection functions (e.g. URL encryption) and their configuration parameters 
                    for the web.xml can be found in the WebCastellum Reference Guide.
      -->
    </filter>
----

.. Filter-Mappings Definition for dispatcher modes request, include and forward

[source,xml]
----
       <filter-mapping>
           <filter-name>WebCastellum</filter-name>
           <url-pattern>/*</url-pattern>
           <dispatcher>REQUEST</dispatcher>
           <dispatcher>INCLUDE</dispatcher>
           <dispatcher>FORWARD</dispatcher>
       </filter-mapping>
----

IMPORTANT: If other servlet filters are configured in the web.xml of the application, WebCastellum is usually configured as the “first” filter, i.e. as the filter that the request passes through first. 
All other filters must always be run afterwards. One exception, however, are special compression filters. These are (if available) exceptionally configured before WebCastellum in the web.xml, so that the responses are compression of the responses takes place after they are transferred to WebCastellum are transferred.  

It should also be noted that for all other filters of the application (if it has any) the dispatcher setting in the filter mapping is also extended to “FORWARD” in addition to “REQUEST” so that the WebCastellum functions take effect accordingly. Especially when use of URL encryption, it is important that the filters of the application are also set to “FORWARD” are also set.

=== Examples of configuration options

The individual security features in the web.xml can be activated bit by bit as part of the further protection. The following consecutive security features are particularly suitable for demonstrating the increasing level of protection. The following configuration settings exist for this purpose.
Configuration settings, which can be set to “true” in web.xml, for example:

==== "SecretTokenLinkInjection"

When this security feature is activated, randomly generated tokens are injected into links and forms and cross-checked (e.g. for further
protection against CSRF attacks).

