name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CATALINA_HOME: /home/runner/work/webcastellum/webcastellum/apache-tomcat-8.5.78
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: install tomcat
        run: |
            wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
            mkdir tomcat
            tar zxf apache-tomcat-8.5.78.tar.gz
            sed -i '/<\/tomcat-users>/ i\<user username="arquillian" password="arquillian" roles="manager-script"/>' apache-tomcat-8.5.78/conf/tomcat-users.xml
      - name: additional dependencies
        run: |
            wget https://repository.jboss.org/nexus/content/groups/public/javax/jms/jms/1.1/jms-1.1.jar
            wget https://repo1.maven.org/maven2/javax/mail/mail/1.5.0-b01/mail-1.5.0-b01.jar
            mvn install:install-file -Dfile=jms-1.1.jar -DgroupId=javax.jms -DartifactId=jms -Dversion=1.1 -Dpackaging=jar
            mvn install:install-file -Dfile=mail-1.5.0-b01.jar -DgroupId=javax.mail -DartifactId=mail -Dversion=1.5.0-b01 -Dpackaging=jar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn package -P tomcat -Dmaven.test.skip=true
      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -P tomcat org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devtty_webcastellum

